#! /bin/bash -e

# The sending mail address
FROM='reminder@mag.lab.sh'

# The target mail address
RCPT='c4fd@lists.open-mail.net'

# The time  to notify before the event occures
LOOKAHEAD='3 days'

# The download URL for the vent list
URL='https://wiki.mag.lab.sh/wiki/Reminder/Events?action=raw'

################################################################################

DATE=$(date --date "now ${LOOKAHEAD}" '+%Y-%m-%d')
EVENT="$(curl -q -k "${URL}" | \
				 grep -e "^ *${DATE}" | \
				 sed 's/^ *//')"

# Check if we found an event
if [[ -z "${EVENT}" ]]; then
  exit 0
fi

# Split the event into variables
  IFS=$(echo -en "\t") \
	read \
	DATE \
	TIME \
	LOCATION \
	SUBJECT \
  <<< "${EVENT}"

# Read the template
TEMPLATE="$(cat template)"

# Generate the message
MESSAGE=$(eval echo "\"${TEMPLATE}\"")

# Send the message
/usr/sbin/sendmail \
  -f "${FROM}" \
  "${RCPT}" \
  <<< "${MESSAGE}"

